### ISSUE TITLE
How do I query for multiple usernames at once?

### ISSUE THREAD

**Issue by TomLewis** [svenluijten/minecraft-php#3]
I have a list of 4000 usernames I need UUID's for, how can I pass this many into this script?
Also how do I print out the UUID of the player?
Also how do I go about printing out all the UUID's as strings after its collected the information?

**Comment by svenluijten** [comment]
Hey! If you're dealing with that many usernames you'd probably want to convert them once and save that result to your database / caching layer / whatever other option you see fit. To get all information you would do something like this:

``` php
$names = [
  // Your 4000 names long array
];

$results = []; // This array will be the result of the script

foreach ($names as $name) {
  $minecraft = new Minecraft;

  $results[$name] = $minecraft->fromName($name)->only('uuid');
}
```

Your `$results` variable will now look something like this:

``` php
[
  'username' => 'that_users_uuid',
  'othername' => 'this_persons_uuid',

  // etc
]
```

I hope this helps! :smile:
