### ISSUE TITLE
Application::share not working in Laravel 5.4

### ISSUE THREAD

**Issue by RamonSmit** [svenluijten/minecraft-php#4]
Hi! 

The share method has been taken out in Laravel 5.4, so this package is broken in that Laravel version. 

You can solve the problem by using the singleton method tho. 

Can you please take a look at that?

**Comment by svenluijten** [comment]
Thanks for pointing that out! I've updated the service provider and tagged [a new release](https://github.com/svenluijten/minecraft-php/releases/tag/v0.0.4).

**Comment by RamonSmit** [comment]
Thank you very much!
